[package]
name = "mdbook-private"
version = "0.1.1"
edition = "2021"
authors = ["Razvan Nicolescu <raz@raztech.io"]
description = "A preprocessor for mdbook that allows for private sections to be hidden or kept"
license = "MPL-2.0"
repository = "https://github.com/RealAtix/mdbook-private"


[dependencies]
clap = "4.4.2"
env_logger = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.20"
mdbook = "0.4.34"
regex = "1.9.5"
semver = "1.0.18"
serde_json = "1.0.105"
